# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created: Tue Jun 24 01:05:44 2014
#      by: PyQt4 UI code generator 4.9.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(800, 570)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.hammingInput = QtGui.QLineEdit(self.centralwidget)
        self.hammingInput.setGeometry(QtCore.QRect(10, 40, 681, 20))
        self.hammingInput.setObjectName(_fromUtf8("hammingInput"))
        self.errorButton = QtGui.QPushButton(self.centralwidget)
        self.errorButton.setGeometry(QtCore.QRect(180, 70, 171, 23))
        self.errorButton.setObjectName(_fromUtf8("errorButton"))
        self.detekcjaButton = QtGui.QPushButton(self.centralwidget)
        self.detekcjaButton.setGeometry(QtCore.QRect(350, 70, 171, 23))
        self.detekcjaButton.setObjectName(_fromUtf8("detekcjaButton"))
        self.korekcjaButton = QtGui.QPushButton(self.centralwidget)
        self.korekcjaButton.setGeometry(QtCore.QRect(520, 70, 171, 23))
        self.korekcjaButton.setObjectName(_fromUtf8("korekcjaButton"))
        self.label_20 = QtGui.QLabel(self.centralwidget)
        self.label_20.setGeometry(QtCore.QRect(10, 20, 301, 16))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_20.setFont(font)
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.encodeButton = QtGui.QPushButton(self.centralwidget)
        self.encodeButton.setGeometry(QtCore.QRect(700, 40, 81, 23))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.encodeButton.setFont(font)
        self.encodeButton.setObjectName(_fromUtf8("encodeButton"))
        self.generateButton = QtGui.QPushButton(self.centralwidget)
        self.generateButton.setGeometry(QtCore.QRect(10, 70, 171, 23))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.generateButton.setFont(font)
        self.generateButton.setObjectName(_fromUtf8("generateButton"))
        self.Skorygowany = QtGui.QTextBrowser(self.centralwidget)
        self.Skorygowany.setGeometry(QtCore.QRect(160, 320, 621, 21))
        self.Skorygowany.setObjectName(_fromUtf8("Skorygowany"))
        self.label_23 = QtGui.QLabel(self.centralwidget)
        self.label_23.setGeometry(QtCore.QRect(10, 230, 131, 20))
        self.label_23.setObjectName(_fromUtf8("label_23"))
        self.label_26 = QtGui.QLabel(self.centralwidget)
        self.label_26.setGeometry(QtCore.QRect(20, 320, 121, 20))
        self.label_26.setObjectName(_fromUtf8("label_26"))
        self.kodHamminga = QtGui.QTextBrowser(self.centralwidget)
        self.kodHamminga.setGeometry(QtCore.QRect(160, 200, 621, 21))
        self.kodHamminga.setStyleSheet(_fromUtf8(""))
        self.kodHamminga.setObjectName(_fromUtf8("kodHamminga"))
        self.l2 = QtGui.QPushButton(self.centralwidget)
        self.l2.setGeometry(QtCore.QRect(540, 430, 16, 21))
        self.l2.setStyleSheet(_fromUtf8("background: white;\n"
"color: rgb(255,153,153);\n"
"font: 9pt \"Arial Black\";"))
        self.l2.setObjectName(_fromUtf8("l2"))
        self.l3 = QtGui.QPushButton(self.centralwidget)
        self.l3.setGeometry(QtCore.QRect(540, 460, 16, 21))
        self.l3.setStyleSheet(_fromUtf8("background: white;\n"
"color: rgb(178,255,102);\n"
"font: 9pt \"Arial Black\";\n"
""))
        self.l3.setObjectName(_fromUtf8("l3"))
        self.label_25 = QtGui.QLabel(self.centralwidget)
        self.label_25.setGeometry(QtCore.QRect(20, 290, 121, 16))
        self.label_25.setObjectName(_fromUtf8("label_25"))
        self.l1 = QtGui.QPushButton(self.centralwidget)
        self.l1.setGeometry(QtCore.QRect(540, 400, 16, 21))
        self.l1.setStyleSheet(_fromUtf8("background: white;\n"
"color: rgb(153,153,255);\n"
"font: 9pt \"Arial Black\";"))
        self.l1.setObjectName(_fromUtf8("l1"))
        self.label_4 = QtGui.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(570, 460, 201, 21))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.HammingWithError = QtGui.QTextBrowser(self.centralwidget)
        self.HammingWithError.setGeometry(QtCore.QRect(160, 260, 621, 21))
        self.HammingWithError.setObjectName(_fromUtf8("HammingWithError"))
        self.label_21 = QtGui.QLabel(self.centralwidget)
        self.label_21.setGeometry(QtCore.QRect(20, 200, 131, 16))
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.WektorBledu = QtGui.QTextBrowser(self.centralwidget)
        self.WektorBledu.setGeometry(QtCore.QRect(160, 230, 621, 21))
        self.WektorBledu.setObjectName(_fromUtf8("WektorBledu"))
        self.clearOutHam = QtGui.QPushButton(self.centralwidget)
        self.clearOutHam.setGeometry(QtCore.QRect(680, 350, 101, 23))
        self.clearOutHam.setObjectName(_fromUtf8("clearOutHam"))
        self.label_3 = QtGui.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(570, 430, 171, 21))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.DetekcjaB = QtGui.QTextBrowser(self.centralwidget)
        self.DetekcjaB.setGeometry(QtCore.QRect(160, 290, 621, 21))
        self.DetekcjaB.setObjectName(_fromUtf8("DetekcjaB"))
        self.label = QtGui.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(540, 360, 151, 31))
        self.label.setObjectName(_fromUtf8("label"))
        self.label_22 = QtGui.QLabel(self.centralwidget)
        self.label_22.setGeometry(QtCore.QRect(0, 260, 171, 16))
        self.label_22.setObjectName(_fromUtf8("label_22"))
        self.label_2 = QtGui.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(570, 400, 171, 21))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.pokazG = QtGui.QPushButton(self.centralwidget)
        self.pokazG.setGeometry(QtCore.QRect(50, 430, 231, 23))
        self.pokazG.setObjectName(_fromUtf8("pokazG"))
        self.pokazH = QtGui.QPushButton(self.centralwidget)
        self.pokazH.setGeometry(QtCore.QRect(50, 460, 231, 23))
        self.pokazH.setObjectName(_fromUtf8("pokazH"))
        self.pokazSposob = QtGui.QPushButton(self.centralwidget)
        self.pokazSposob.setGeometry(QtCore.QRect(50, 490, 231, 23))
        self.pokazSposob.setObjectName(_fromUtf8("pokazSposob"))
        self.syndrom = QtGui.QTextBrowser(self.centralwidget)
        self.syndrom.setGeometry(QtCore.QRect(160, 350, 361, 21))
        self.syndrom.setObjectName(_fromUtf8("syndrom"))
        self.label_27 = QtGui.QLabel(self.centralwidget)
        self.label_27.setGeometry(QtCore.QRect(20, 350, 121, 20))
        self.label_27.setObjectName(_fromUtf8("label_27"))
        self.buttonLista = QtGui.QPushButton(self.centralwidget)
        self.buttonLista.setGeometry(QtCore.QRect(50, 400, 231, 23))
        self.buttonLista.setObjectName(_fromUtf8("buttonLista"))
        self.label_24 = QtGui.QLabel(self.centralwidget)
        self.label_24.setGeometry(QtCore.QRect(10, 110, 301, 16))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_24.setFont(font)
        self.label_24.setObjectName(_fromUtf8("label_24"))
        self.dekodujInput = QtGui.QLineEdit(self.centralwidget)
        self.dekodujInput.setGeometry(QtCore.QRect(10, 130, 681, 20))
        self.dekodujInput.setObjectName(_fromUtf8("dekodujInput"))
        self.decodeButton = QtGui.QPushButton(self.centralwidget)
        self.decodeButton.setGeometry(QtCore.QRect(700, 130, 81, 23))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.decodeButton.setFont(font)
        self.decodeButton.setObjectName(_fromUtf8("decodeButton"))
        self.buttonBledy = QtGui.QPushButton(self.centralwidget)
        self.buttonBledy.setGeometry(QtCore.QRect(50, 520, 231, 23))
        self.buttonBledy.setObjectName(_fromUtf8("buttonBledy"))
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "Kodowanie Hamminga", None, QtGui.QApplication.UnicodeUTF8))
        self.errorButton.setText(QtGui.QApplication.translate("MainWindow", "Wektor Błędu", None, QtGui.QApplication.UnicodeUTF8))
        self.detekcjaButton.setText(QtGui.QApplication.translate("MainWindow", "Detekcja", None, QtGui.QApplication.UnicodeUTF8))
        self.korekcjaButton.setText(QtGui.QApplication.translate("MainWindow", "Korekcja", None, QtGui.QApplication.UnicodeUTF8))
        self.label_20.setText(QtGui.QApplication.translate("MainWindow", "Podaj binararną informacje do zakodowania", None, QtGui.QApplication.UnicodeUTF8))
        self.encodeButton.setText(QtGui.QApplication.translate("MainWindow", "Koduj", None, QtGui.QApplication.UnicodeUTF8))
        self.generateButton.setToolTip(QtGui.QApplication.translate("MainWindow", "<html><head/><body><p>Generuje losowy ciąg binarny</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.generateButton.setWhatsThis(QtGui.QApplication.translate("MainWindow", "<html><head/><body><p>Generuje losowy ciąg binarny</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.generateButton.setText(QtGui.QApplication.translate("MainWindow", "Generuj Losowo", None, QtGui.QApplication.UnicodeUTF8))
        self.label_23.setText(QtGui.QApplication.translate("MainWindow", "      Wektor błędu", None, QtGui.QApplication.UnicodeUTF8))
        self.label_26.setText(QtGui.QApplication.translate("MainWindow", "Skorygowany kod ", None, QtGui.QApplication.UnicodeUTF8))
        self.l2.setText(QtGui.QApplication.translate("MainWindow", "X", None, QtGui.QApplication.UnicodeUTF8))
        self.l3.setText(QtGui.QApplication.translate("MainWindow", "X", None, QtGui.QApplication.UnicodeUTF8))
        self.label_25.setText(QtGui.QApplication.translate("MainWindow", "  Detekcja błędu", None, QtGui.QApplication.UnicodeUTF8))
        self.l1.setText(QtGui.QApplication.translate("MainWindow", "X", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("MainWindow", "- pozycja skorygowanego błędu", None, QtGui.QApplication.UnicodeUTF8))
        self.label_21.setText(QtGui.QApplication.translate("MainWindow", "  Kod Hamminga", None, QtGui.QApplication.UnicodeUTF8))
        self.clearOutHam.setToolTip(QtGui.QApplication.translate("MainWindow", "<html><head/><body><p>Czyści output</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.clearOutHam.setText(QtGui.QApplication.translate("MainWindow", "Clear", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("MainWindow", "- pozycja błędu", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("MainWindow", "LEGENDA:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_22.setText(QtGui.QApplication.translate("MainWindow", "Kod Hamminga z błędem", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("MainWindow", "- miejsca bitów parzystości", None, QtGui.QApplication.UnicodeUTF8))
        self.pokazG.setText(QtGui.QApplication.translate("MainWindow", "Pokaż macierz G", None, QtGui.QApplication.UnicodeUTF8))
        self.pokazH.setText(QtGui.QApplication.translate("MainWindow", "Pokaż macierz H", None, QtGui.QApplication.UnicodeUTF8))
        self.pokazSposob.setText(QtGui.QApplication.translate("MainWindow", "Pokaż sposób detekcji bledu", None, QtGui.QApplication.UnicodeUTF8))
        self.label_27.setText(QtGui.QApplication.translate("MainWindow", "      Syndrom", None, QtGui.QApplication.UnicodeUTF8))
        self.buttonLista.setText(QtGui.QApplication.translate("MainWindow", "Lista kodów ", None, QtGui.QApplication.UnicodeUTF8))
        self.label_24.setText(QtGui.QApplication.translate("MainWindow", "Podaj binararną informacje do dekodowania", None, QtGui.QApplication.UnicodeUTF8))
        self.decodeButton.setText(QtGui.QApplication.translate("MainWindow", "Dekoduj", None, QtGui.QApplication.UnicodeUTF8))
        self.buttonBledy.setText(QtGui.QApplication.translate("MainWindow", "Lista błędów", None, QtGui.QApplication.UnicodeUTF8))

